version: "3.9"
services:
  exam-app:
    container_name: hospital-webserver
    restart: always
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    command: bash -c "gem install rake rack sinatra puma pg && rake build_schema && ruby server.rb"
    ports:
      - "3000:3000"
    networks:
      - exam
  med-db:
    container_name: hospital-db
    restart: always
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hospital
      - POSTGRES_USER=exam
      - POSTGRES_PASSWORD=exam
    networks:
      - exam
  test-db:
    container_name: test-db
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=hospital
      - POSTGRES_USER=exam
      - POSTGRES_PASSWORD=exam
    networks:
      - exam
volumes:
  pgdata:
  bundle:
networks:
  exam: